name: boxtout
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  carousel_slider: ^4.2.1
  url_strategy: ^0.2.0
  badges: ^3.1.1
  flutter_screenutil: ^5.8.4
  auto_size_text: ^3.0.0
  another_transformer_page_view: ^2.0.1
  smooth_page_indicator: ^1.1.0
  firebase_core: ^2.15.0
  supabase_flutter: ^1.10.10
  firebase_auth: ^4.7.2
  collection: ^1.17.0
  freezed_annotation: ^2.0.3
  json_annotation: ^4.8.1
  stacked: ^3.4.1
  stacked_services: ^1.2.0
  stacked_themes: ^0.3.12
  reactive_forms: ^16.0.2
  reactive_date_time_picker: ^3.0.0
  reactive_forms_annotations: ^4.0.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  google_fonts: ^4.0.3
  intl: ^0.18.0
  uuid: ^3.0.7
  responsive_builder: ^0.7.0
  flutter_animate: ^4.2.0
  cached_network_image: ^3.2.0
  flutter_native_splash: ^2.2.19
  dartz: ^0.10.1

dev_dependencies:
  build_runner: ^2.4.5
  json_serializable: ^6.7.1
  mockito: ^5.4.1
  freezed: ^2.3.5
  stacked_generator: ^1.4.0
  hive_generator: ^2.0.0
  reactive_forms_generator: ^4.0.0
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  
  
  

flutter:
  assets:
    - assets/
    - assets/sliders/
  uses-material-design: true

